#!/bin/bash
# Generated by scripts/publish-deploy.ts. Run on the server:
#   cd ~/repositories/appointment && git pull && bash deploy.sh
set -e
cd "$(dirname "$0")"
DEST="$HOME/public_html/report"
mkdir -p "$DEST"
rm -rf "$DEST/assets"
for f in * .htaccess; do
  [ "$f" = deploy.sh ] && continue
  cp -R "$f" "$DEST/"
done
echo "Deployed $(git log -1 --format=%s) to $DEST"
