/**
 * Writes supabase/seed.sql from src/data/seedTeachers.ts.
 * Run: npm run seed:generate
 */
import { writeFileSync } from 'node:fs';
import { parseSeed } from '../src/data/seedTeachers.ts';

const q = (v: string | null) => (v === null ? 'null' : `'${v.replace(/'/g, "''")}'`);

export function buildSeedSql(): string {
  const all = parseSeed();
  const insert = (level: 'sd' | 'smp_sma') => {
    const rows = all
      .filter((t) => t.level === level)
      .map(
        (t) =>
          `  (${q(t.name)}, ${q(t.subject)}, '{${t.grades.join(',')}}'::int[], ${q(t.role)}, ${q(t.homeroomClass)}, ` +
          `${t.isLeadership}, ${q(t.room)}, ${t.available}, ${t.sortOrder}, '${level}')`,
      );
    return `insert into public.teachers (name, subject, grades, role, homeroom_class, is_leadership, room, available, sort_order, level)
select * from (values
${rows.join(',\n')}
) as v(name, subject, grades, role, homeroom_class, is_leadership, room, available, sort_order, level)
where not exists (select 1 from public.teachers where level = '${level}');
`;
  };
  return `-- Generated by \`npm run seed:generate\` from src/data/seedTeachers.ts. Do not edit by hand.
-- Inserts each level's starting list ONLY if that level has no teachers yet,
-- so it is safe to run again. After setup, edit teachers from the Admin page.

-- SMP–SMA teachers
${insert('smp_sma')}
-- SD classes (one record per class: its two homeroom teachers)
${insert('sd')}`;
}

if (import.meta.url === `file:///${process.argv[1].replace(/\\/g, '/')}` || process.argv[1]?.endsWith('generate-seed.ts')) {
  writeFileSync(new URL('../supabase/seed.sql', import.meta.url), buildSeedSql());
  console.log('Wrote supabase/seed.sql');
}
